sonar.projectKey=fortnite-pronos-frontend
sonar.projectName=Fortnite Pronos Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,src/main.ts,src/environments/**
sonar.coverage.exclusions=src/**/*.spec.ts

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.scm.provider=git
