ALTER TABLE games
  ADD COLUMN IF NOT EXISTS draft_mode       VARCHAR(20)  NOT NULL DEFAULT 'SNAKE',
  ADD COLUMN IF NOT EXISTS team_size        INTEGER      NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS tranche_size     INTEGER      NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS tranches_enabled BOOLEAN      NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS competition_start DATE,
  ADD COLUMN IF NOT EXISTS competition_end   DATE;
